/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: b69df602b64b1ee70dcdd09d87c2a7a2)
interface __BaseEnv_Env {
	SESSION_MEMORY: KVNamespace;
	TELEGRAM_JOBS: Queue;
	AGENT_RUNTIME: string;
	LINE_API_BASE_URL: string;
	TELEGRAM_API_BASE_URL: string;
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_API_BASE_URL: string;
	WHATSAPP_API_BASE_URL: string;
	WHATSAPP_ACCESS_TOKEN: string;
	WHATSAPP_PHONE_NUMBER_ID: string;
	WHATSAPP_VERIFY_TOKEN: string;
	WHATSAPP_APP_SECRET: string;
	OPENAI_BASE_URL: string;
	OPENAI_MODEL: string;
	OPENAI_MAX_TOOL_ROUNDS: string;
	OPENAI_MAX_TOOL_CALLS: string;
	GITHUB_API_BASE_URL: string;
	GITHUB_REF: string;
	SESSION_MEMORY_MAX_MESSAGES: string;
	HERMES_BASE_URL: string;
	HERMES_TELEGRAM_ALLOWED_USER_IDS: string;
	QUEUE_FAILURE_EVENT_SECRET: string;
	QUEUE_FAILURE_DISCORD_CHANNEL_ID: string;
	DATABASE_ADAPTER_URL: string;
	DATABASE_ADAPTER_TOKEN?: string;
	DATABASE_DATASOURCE: string;
	DATABASE_ALLOWED_SCHEMAS: string;
	DATABASE_ALLOWED_TABLES: string;
	ARTIFACT_RENDERER_URL: string;
	ARTIFACT_RENDERER_TOKEN?: string;
	ARTIFACT_SCREENSHOT_TARGETS_JSON: string;
	DEPLOY_TARGETS_JSON: string;
	DEPLOY_EXECUTOR_TOKEN?: string;
	LINE_CHANNEL_SECRET: string;
	LINE_CHANNEL_ACCESS_TOKEN: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_WEBHOOK_SECRET: string;
	TELEGRAM_ALLOWED_USER_IDS: string;
	DISCORD_ALLOWED_USER_IDS: string;
	DISCORD_BOT_TOKEN: string;
	DISCORD_GATEWAY_SHARED_SECRET: string;
	DISCORD_ALLOWED_GUILD_IDS: string;
	OPENAI_API_KEY: string;
	GITHUB_TOKEN: string;
	HERMES_API_SERVER_KEY: string;
	TELEGRAM_SESSION_COORDINATOR: DurableObjectNamespace<
		import("./src/worker").TelegramSessionCoordinator
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "TelegramSessionCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				| "AGENT_RUNTIME"
				| "LINE_API_BASE_URL"
				| "TELEGRAM_API_BASE_URL"
				| "DISCORD_APPLICATION_ID"
				| "DISCORD_PUBLIC_KEY"
				| "DISCORD_API_BASE_URL"
				| "WHATSAPP_API_BASE_URL"
				| "WHATSAPP_ACCESS_TOKEN"
				| "WHATSAPP_PHONE_NUMBER_ID"
				| "WHATSAPP_VERIFY_TOKEN"
				| "WHATSAPP_APP_SECRET"
				| "OPENAI_BASE_URL"
				| "OPENAI_MODEL"
				| "OPENAI_MAX_TOOL_ROUNDS"
				| "OPENAI_MAX_TOOL_CALLS"
				| "GITHUB_API_BASE_URL"
				| "GITHUB_REF"
				| "SESSION_MEMORY_MAX_MESSAGES"
				| "HERMES_BASE_URL"
				| "HERMES_TELEGRAM_ALLOWED_USER_IDS"
				| "QUEUE_FAILURE_EVENT_SECRET"
				| "QUEUE_FAILURE_DISCORD_CHANNEL_ID"
				| "LINE_CHANNEL_SECRET"
				| "LINE_CHANNEL_ACCESS_TOKEN"
				| "TELEGRAM_BOT_TOKEN"
				| "TELEGRAM_WEBHOOK_SECRET"
				| "TELEGRAM_ALLOWED_USER_IDS"
				| "DISCORD_ALLOWED_USER_IDS"
				| "DISCORD_BOT_TOKEN"
				| "DISCORD_GATEWAY_SHARED_SECRET"
				| "DISCORD_ALLOWED_GUILD_IDS"
				| "OPENAI_API_KEY"
				| "GITHUB_TOKEN"
				| "HERMES_API_SERVER_KEY"
			>
		> {}
}
declare module "*.md" {
	const value: string;
	export default value;
}
